### ISSUE TITLE
Create all default renpy screens

### ISSUE THREAD

**Issue by BlackRam-oss** [DRincs-Productions/pixi-vn-react#7]
- [x] DRincs-Productions/pixi-vn#5
- [ ] save menu
- [x] DRincs-Productions/pixi-vn#9
- [x] DRincs-Productions/pixi-vn#70
- [ ] DRincs-Productions/pixi-vn-react#1
- [ ] about
- [ ] Route not found / Error Screen
